### ISSUE TITLE
Links in the download page should be `https` instead of `http`

### ISSUE THREAD

**Issue by petmakris** [LinuxCNC/wlo#25]
Most browsers won't download the iso files if the link is `http` from an `https` website

**Comment by petmakris** [comment]
[[<a href="https://ibb.co/3kBK5b5"><img src="https://i.ibb.co/rv49KhK/285091771-720267912630491-2693771721359771058-n.png" alt="285091771-720267912630491-2693771721359771058-n" border="0"></a>](https://ibb.co/3kBK5b5)](https://ibb.co/3kBK5b5)

**Comment by andypugh** [comment]
Do you think this is as simple as just adding an "s" to https://raw.githubusercontent.com/LinuxCNC/wlo/master/downloads/index.md

**Comment by petmakris** [comment]
Relative link would be a better solution, agnostic of both the protocol and the domain name, but I have to test this
